In [1]:
from daily_forecast import import_data, create_forecast_dates, map_calendar, map_holidays, map_snaps
from daily_forecast import rank_products, filter_product, unpivot_weeks
from daily_forecast import join_snaps, join_dates, tag_train_eval, join_holidays, join_prices, include_diff_dates
from daily_forecast import boxcox_transform

In [2]:
df_raw, calendar, price = import_data()

In [3]:
df_raw = create_forecast_dates(df_raw)

In [4]:
mapping_calendar = map_calendar(calendar)
holidays = map_holidays(calendar)
snaps = map_snaps(calendar)

In [5]:
sorted_products = rank_products(df_raw)
id = sorted_products.index[0]

In [6]:
df = filter_product(df_raw, id)

In [7]:
df = unpivot_weeks(df)

In [8]:
df = join_snaps(df, snaps)

In [9]:
df = join_dates(df, mapping_calendar)

In [10]:
df = tag_train_eval(df)

In [11]:
df = join_holidays(df, holidays)

In [12]:
df = join_prices(df, price)

In [13]:
df = include_diff_dates(df)

In [14]:
df, boxcox_lambda = boxcox_transform(df)

In [15]:
df

,id,value,snap,date,weekday,month,year,eval_set,holiday,sell_price,dt,dt2,adj_value
0,FOODS_3_090_CA_3_validation,108,0,2011-01-29,5_Sat,1,2011,False,0,1.25,0,0,14.934158
1,FOODS_3_090_CA_3_validation,132,0,2011-01-30,6_Sun,1,2011,False,0,1.25,1,1,16.460409
2,FOODS_3_090_CA_3_validation,102,0,2011-01-31,0_Mon,1,2011,False,0,1.25,2,4,14.522997
3,FOODS_3_090_CA_3_validation,120,1,2011-02-01,1_Tue,2,2011,False,0,1.25,3,9,15.719075
4,FOODS_3_090_CA_3_validation,106,1,2011-02-02,2_Wed,2,2011,False,0,1.25,4,16,14.798583
5,FOODS_3_090_CA_3_validation,123,1,2011-02-03,3_Thu,2,2011,False,0,1.25,5,25,15.908233
6,FOODS_3_090_CA_3_validation,279,1,2011-02-04,4_Fri,2,2011,False,0,1.25,6,36,23.465055
7,FOODS_3_090_CA_3_validation,175,1,2011-02-05,5_Sat,2,2011,False,0,1.25,7,49,18.839993
8,FOODS_3_090_CA_3_validation,186,1,2011-02-06,6_Sun,2,2011,False,SuperBowl,1.25,8,64,19.393343
9,FOODS_3_090_CA_3_validation,120,1,2011-02-07,0_Mon,2,2011,False,0,1.25,9,81,15.719075
10,FOODS_3_090_CA_3_validation,0,1,2011-02-08,1_Tue,2,2011,False,0,1.25,10,100,0.000000
11,FOODS_3_090_CA_3_validation,0,1,2011-02-09,2_Wed,2,2011,False,0,1.25,11,121,0.000000
12,FOODS_3_090_CA_3_validation,0,1,2011-02-10,3_Thu,2,2011,False,0,1.25,12,144,0.000000
13,FOODS_3_090_CA_3_validation,0,0,2011-02-11,4_Fri,2,2011,False,0,1.25,13,169,0.000000
14,FOODS_3_090_CA_3_validation,0,0,2011-02-12,5_Sat,2,2011,False,0,1.25,14,196,0.000000
15,FOODS_3_090_CA_3_validation,0,0,2011-02-13,6_Sun,2,2011,False,0,1.25,15,225,0.000000
16,FOODS_3_090_CA_3_validation,0,0,2011-02-14,0_Mon,2,2011,False,ValentinesDay,1.25,16,256,0.000000
17,FOODS_3_090_CA_3_validation,0,0,2011-02-15,1_Tue,2,2011,False,0,1.25,17,289,0.000000
18,FOODS_3_090_CA_3_validation,0,0,2011-02-16,2_Wed,2,2011,False,0,1.25,18,324,0.000000
19,FOODS_3_090_CA_3_validation,0,0,2011-02-17,3_Thu,2,2011,False,0,1.25,19,361,0.000000
20,FOODS_3_090_CA_3_validation,0,0,2011-02-18,4_Fri,2,2011,False,0,1.25,20,400,0.000000
21,FOODS_3_090_CA_3_validation,0,0,2011-02-19,5_Sat,2,2011,False,0,1.25,21,441,0.000000
22,FOODS_3_090_CA_3_validation,0,0,2011-02-20,6_Sun,2,2011,False,0,1.25,22,484,0.000000
23,FOODS_3_090_CA_3_validation,0,0,2011-02-21,0_Mon,2,2011,False,0,1.25,23,529,0.000000
24,FOODS_3_090_CA_3_validation,0,0,2011-02-22,1_Tue,2,2011,False,0,1.25,24,576,0.000000
25,FOODS_3_090_CA_3_validation,0,0,2011-02-23,2_Wed,2,2011,False,0,1.25,25,625,0.000000
26,FOODS_3_090_CA_3_validation,0,0,2011-02-24,3_Thu,2,2011,False,0,1.25,26,676,0.000000
27,FOODS_3_090_CA_3_validation,0,0,2011-02-25,4_Fri,2,2011,False,0,1.25,27,729,0.000000
28,FOODS_3_090_CA_3_validation,0,0,2011-02-26,5_Sat,2,2011,False,0,1.25,28,784,0.000000
29,FOODS_3_090_CA_3_validation,0,0,2011-02-27,6_Sun,2,2011,False,0,1.25,29,841,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,FOODS_3_090_CA_3_validation,139,0,2016-04-23,5_Sat,4,2016,False,0,1.60,1911,3651921,16.875189
1912,FOODS_3_090_CA_3_validation,130,0,2016-04-24,6_Sun,4,2016,False,0,1.60,1912,3655744,16.339605
1913,FOODS_3_090_CA_3_validation,0,0,2016-04-25,0_Mon,4,2016,True,0,1.60,1913,3659569,0.000000
1914,FOODS_3_090_CA_3_validation,0,0,2016-04-26,1_Tue,4,2016,True,0,1.60,1914,3663396,0.000000
1915,FOODS_3_090_CA_3_validation,0,0,2016-04-27,2_Wed,4,2016,True,0,1.60,1915,3667225,0.000000
1916,FOODS_3_090_CA_3_validation,0,0,2016-04-28,3_Thu,4,2016,True,0,1.60,1916,3671056,0.000000
1917,FOODS_3_090_CA_3_validation,0,0,2016-04-29,4_Fri,4,2016,True,0,1.60,1917,3674889,0.000000
1918,FOODS_3_090_CA_3_validation,0,0,2016-04-30,5_Sat,4,2016,True,0,1.60,1918,3678724,0.000000
1919,FOODS_3_090_CA_3_validation,0,1,2016-05-01,6_Sun,5,2016,True,0,1.60,1919,3682561,0.000000
1920,FOODS_3_090_CA_3_validation,0,1,2016-05-02,0_Mon,5,2016,True,0,1.60,1920,3686400,0.000000
1921,FOODS_3_090_CA_3_validation,0,1,2016-05-03,1_Tue,5,2016,True,0,1.60,1921,3690241,0.000000
1922,FOODS_3_090_CA_3_validation,0,1,2016-05-04,2_Wed,5,2016,True,0,1.60,1922,3694084,0.000000
1923,FOODS_3_090_CA_3_validation,0,1,2016-05-05,3_Thu,5,2016,True,0,1.60,1923,3697929,0.000000
1924,FOODS_3_090_CA_3_validation,0,1,2016-05-06,4_Fri,5,2016,True,0,1.60,1924,3701776,0.000000
1925,FOODS_3_090_CA_3_validation,0,1,2016-05-07,5_Sat,5,2016,True,0,1.60,1925,3705625,0.000000
1926,FOODS_3_090_CA_3_validation,0,1,2016-05-08,6_Sun,5,2016,True,Mother's day,1.60,1926,3709476,0.000000
1927,FOODS_3_090_CA_3_validation,0,1,2016-05-09,0_Mon,5,2016,True,0,1.60,1927,3713329,0.000000
1928,FOODS_3_090_CA_3_validation,0,1,2016-05-10,1_Tue,5,2016,True,0,1.60,1928,3717184,0.000000
1929,FOODS_3_090_CA_3_validation,0,0,2016-05-11,2_Wed,5,2016,True,0,1.60,1929,3721041,0.000000
1930,FOODS_3_090_CA_3_validation,0,0,2016-05-12,3_Thu,5,2016,True,0,1.60,1930,3724900,0.000000
1931,FOODS_3_090_CA_3_validation,0,0,2016-05-13,4_Fri,5,2016,True,0,1.60,1931,3728761,0.000000
1932,FOODS_3_090_CA_3_validation,0,0,2016-05-14,5_Sat,5,2016,True,0,1.60,1932,3732624,0.000000
1933,FOODS_3_090_CA_3_validation,0,0,2016-05-15,6_Sun,5,2016,True,0,1.60,1933,3736489,0.000000
1934,FOODS_3_090_CA_3_validation,0,0,2016-05-16,0_Mon,5,2016,True,0,1.60,1934,3740356,0.000000
1935,FOODS_3_090_CA_3_validation,0,0,2016-05-17,1_Tue,5,2016,True,0,1.60,1935,3744225,0.000000
1936,FOODS_3_090_CA_3_validation,0,0,2016-05-18,2_Wed,5,2016,True,0,1.60,1936,3748096,0.000000
1937,FOODS_3_090_CA_3_validation,0,0,2016-05-19,3_Thu,5,2016,True,0,1.60,1937,3751969,0.000000
1938,FOODS_3_090_CA_3_validation,0,0,2016-05-20,4_Fri,5,2016,True,0,1.60,1938,3755844,0.000000
1939,FOODS_3_090_CA_3_validation,0,0,2016-05-21,5_Sat,5,2016,True,0,1.60,1939,3759721,0.000000
1940,FOODS_3_090_CA_3_validation,0,0,2016-05-22,6_Sun,5,2016,True,0,1.60,1940,3763600,0.000000